//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult, ts_rs::TS)]
pub struct GoogleCalendarSettings {
    pub google_calendar_api_key: String,
    pub google_oauth_client_id: String,
    pub google_oauth_secret: String,
    #[ts(as = "String")]
    pub google_oauth_redirect_uri_base: url::Url,
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "admin_settings")]
#[ts(export, rename = "AdminSettings")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub allow_new_registrations: bool,
    #[sea_orm(column_type = "JsonBinary", nullable)]
    pub google_calendar_settings: Option<GoogleCalendarSettings>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}
