//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "appointments")]
#[ts(export, rename = "Appointment")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub booker_name: String,
    pub booker_phone: String,
    pub booker_timezone: String,
    pub booker_email: String,
    pub start_time: DateTimeWithTimeZone,
    pub endtime: DateTimeWithTimeZone,
    pub status: String,
    pub user_id: i32,
    pub appointment_type_id: i32,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::appointment_types::Entity",
        from = "Column::AppointmentTypeId",
        to = "super::appointment_types::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    AppointmentTypes,
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::appointment_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppointmentTypes.def()
    }
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
