//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use std::collections::HashSet;

use sea_orm::{entity::prelude::*, FromJsonQueryResult};
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Serialize, Deserialize, FromJsonQueryResult, ts_rs :: TS)]
pub struct StringHash(pub HashSet<String>);

impl StringHash {
    pub fn add(&mut self, value: String) {
        self.0.insert(value);
    }

    pub fn remove(&mut self, value: &String) {
        self.0.remove(value);
    }
}

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "google_calendars")]
#[ts(export, rename = "GoogleCalendar")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub access_token: String,
    pub expires_in: i32,
    pub refresh_token: String,
    pub refresh_token_expires_in: Option<i32>,
    pub scope: String,
    pub token_type: String,
    pub user_id: i32,
    #[sea_orm(column_type = "JsonBinary")]
    pub calendars_for_collision_check: StringHash,
    #[sea_orm(column_type = "JsonBinary")]
    pub calendars_for_event_handling: StringHash,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(
        belongs_to = "super::users::Entity",
        from = "Column::UserId",
        to = "super::users::Column::Id",
        on_update = "Cascade",
        on_delete = "Cascade"
    )]
    Users,
}

impl Related<super::users::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Users.def()
    }
}
