//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::admin_settings::Entity as AdminSettings;
pub use super::appointment_types::Entity as AppointmentTypes;
pub use super::appointments::Entity as Appointments;
pub use super::users::Entity as Users;
pub use super::weekly_availabilities::Entity as WeeklyAvailabilities;
