//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize, ts_rs :: TS)]
#[sea_orm(table_name = "users")]
pub struct Model {
    pub created_at: DateTimeWithTimeZone,
    pub updated_at: DateTimeWithTimeZone,
    #[sea_orm(primary_key)]
    pub id: i32,
    pub pid: Uuid,
    #[sea_orm(unique)]
    pub email: String,
    pub password: String,
    #[sea_orm(unique)]
    pub api_key: String,
    pub name: String,
    pub reset_token: Option<String>,
    pub reset_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verification_token: Option<String>,
    pub email_verification_sent_at: Option<DateTimeWithTimeZone>,
    pub email_verified_at: Option<DateTimeWithTimeZone>,
    pub magic_link_token: Option<String>,
    pub magic_link_expiration: Option<DateTimeWithTimeZone>,
    pub timezone: String,
    pub role: Role,
}

#[derive(
    Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize, ts_rs::TS,
)]
#[sea_orm(rs_type = "String", db_type = "String(StringLen::None)")]
pub enum Role {
    #[sea_orm(string_value = "Admin")]
    Admin,
    #[sea_orm(string_value = "User")]
    User,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::appointment_types::Entity")]
    AppointmentTypes,
    #[sea_orm(has_many = "super::appointments::Entity")]
    Appointments,
    #[sea_orm(has_many = "super::google_calendars::Entity")]
    GoogleCalendars,
    #[sea_orm(has_many = "super::oauth_states::Entity")]
    OauthStates,
    #[sea_orm(has_one = "super::user_settings::Entity")]
    UserSettings,
    #[sea_orm(has_many = "super::weekly_availabilities::Entity")]
    WeeklyAvailabilities,
}

impl Related<super::appointment_types::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::AppointmentTypes.def()
    }
}

impl Related<super::appointments::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Appointments.def()
    }
}

impl Related<super::google_calendars::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GoogleCalendars.def()
    }
}

impl Related<super::oauth_states::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::OauthStates.def()
    }
}

impl Related<super::user_settings::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::UserSettings.def()
    }
}

impl Related<super::weekly_availabilities::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WeeklyAvailabilities.def()
    }
}
