// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSettingsParams = { allow_new_registrations: boolean | null, google_cloud_api_key: string | null, };
