// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AdminSettings = { created_at: string, updated_at: string, id: number, allow_new_registrations: boolean, google_cloud_api_key: string | null, };
