// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleCalendarSettings } from "./GoogleCalendarSettings";

export type AdminSettingsParams = { allow_new_registrations: boolean | null, google_calendar_settings: GoogleCalendarSettings | null, };
