// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { GoogleCalendarSettings } from "./GoogleCalendarSettings";

export type AdminSettings = { created_at: string, updated_at: string, id: number, allow_new_registrations: boolean, google_calendar_settings: GoogleCalendarSettings | null, };
