// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type Appointment = { created_at: string, updated_at: string, id: number, booker_name: string, booker_phone: string, booker_timezone: string, booker_email: string, start_time: string, endtime: string, status: string, user_id: number, appointment_type_id: number, };
