// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Appointment } from "./Appointment";

export type AppointmentsResponse = { appointments: Array<Appointment>, count: bigint, };
