// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Status } from "./Status";

export type AppointmentsQueryParams = { page: bigint, limit: bigint, from_date: string | null, to_date: string | null, status: Status | null, appointment_type: number | null, };
