// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormalizedAvailabilityDay } from "./NormalizedAvailabilityDay";
import type { WeeklyAvailability } from "./WeeklyAvailability";

export type AvailabilityDay = { normalized: NormalizedAvailabilityDay, model: WeeklyAvailability, };
