// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type BookingParams = { booker_name: string, booker_phone: string, booker_email: string, from: string, to: string, };
