// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailabilityWindow } from "./AvailabilityWindow";

export type BookDay = { day: string, availabilities: Array<AvailabilityWindow>, };
