// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CalendarSettingType } from "./CalendarSettingType";

export type CalendarSettingParams = { calendar_id: string, setting_type: CalendarSettingType, };
