// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type CalendarEntry = { access_role: string, background_color: string, foreground_color: string, id: string, primary: boolean, selected: boolean, summary: string, time_zone: string, };
