// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { StringHash } from "./StringHash";

export type GoogleCalendar = { created_at: string, updated_at: string, id: number, access_token: string, expires_in: number, refresh_token: string, scope: string, token_type: string, user_id: number, calendars_for_collision_check: StringHash, calendars_for_event_handling: StringHash, };
