// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleCalendarSettings = { google_calendar_api_key: string, google_oauth_client_id: string, google_oauth_secret: string, google_oauth_redirect_uri_base: string, };
