// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type GoogleCalendar = { created_at: string, updated_at: string, id: number, access_token: string, expires_in: number, refresh_token: string, refresh_token_expires_in: number, scope: string, token_type: string, user_id: number, };
