// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Normalizes availability to 0 minutes min and 1440 minutes max
 */
export type NormalizedAvailabilityDay = { from: number, to: number, };
