// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OAuthState = { created_at: string, updated_at: string, id: string, user_id: number, };
