// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UpdateAppointmentTypeParams = { duration_in_minutes: number, display_name: string, };
