// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DaysHoursMinutes } from "./DaysHoursMinutes";

export type UserSettingsProps = { start_how_far_from_now: DaysHoursMinutes, end_how_far_from_now: DaysHoursMinutes, };
