// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type UserSettings = { created_at: string, updated_at: string, id: number, user_id: number, start_how_far_from_now_in_minutes: number, end_how_far_from_now_in_minutes: number, };
