// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NormalizedAvailabilityDay } from "./NormalizedAvailabilityDay";

export type WeeklyAvailabilitiesCreateUpdateParams = { normalized: NormalizedAvailabilityDay, 
/**
 * Zero indexed weekday (0 = Monday, 1 = Tuesday, etc.)
 */
weekday: number, };
