// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type WeeklyAvailability = { created_at: string, updated_at: string, id: number, from: number, to: number, user_id: number, };
