// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AvailabilityDay } from "./AvailabilityDay";

export type WeeklyAvailabilityByWeekday = { monday: Array<AvailabilityDay>, tuesday: Array<AvailabilityDay>, wednesday: Array<AvailabilityDay>, thursday: Array<AvailabilityDay>, friday: Array<AvailabilityDay>, saturday: Array<AvailabilityDay>, sunday: Array<AvailabilityDay>, };
